### ISSUE TITLE
Filenames mis-handled when passing directory paths with trailing slash (e.g dir1\ dir2\)

### ISSUE THREAD

**Issue by INSYG** [Zoltanar/Agf2Bmp2Agf#1]
When running the program with the command `AGF2BMP2AGF -u dir1\ dir2\`, the filename of any file within the `dir1` folder will not be reflected properly in the filename of the resulting file in the `dir2` folder. The console will also display the incorrect filename. For example, a file `dir1/CN001A.AGF` will be converted into the file `dir2/N001A.BMP`, and the console will display `1 N001A.AGF->N001A.BMP`.

Similarly, when running the program with the command `AGF2BMP2AGF -p dir2\ dir3\ dir1\`, the program cannot find the original file located in the `dir1` folder, even if the file name is manually restored to `CN001A.BMP`, as it is attempting to find the file named `N001A.AGF`. Renaming the file to `aCN001A.BMP` produces the intended result, outputting the file `dir3/CN001A.AGF`.

**Comment by Zoltanar** [comment]
Thanks for the report, the issue was the trailing slash (\) at the end, in the meantime, you can exclude them to work around the issue.
So you would run the command `AGF2BMP2AGF -u dir1 dir2` instead.

**Comment by Zoltanar** [comment]
Fixed in e90409b39efc423795b8a482d57b41cf481f3a58
